name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create and Modify Archive
        run: |
          mkdir temp
          cd temp
          git -C .. archive --format=zip --output=../release.zip HEAD
          unzip ../release.zip
          mv * upcoder-admin-menu
          zip -r ../release.zip upcoder-admin-menu
          cd ..
          rm -rf temp
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip