name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create and Modify Archive
        run: |
          # Créer l'archive sans dossier racine
          git archive --output=temp.zip HEAD
          
          # Créer un dossier temporaire
          mkdir temp
          cd temp
          
          # Extraire les fichiers
          unzip ../temp.zip
          
          # Créer le dossier avec le nom souhaité et déplacer tous les fichiers dedans
          mkdir upcoder-admin-menu
          mv $(ls -A | grep -v 'upcoder-admin-menu') upcoder-admin-menu/
          
          # Créer la nouvelle archive
          zip -r ../release.zip upcoder-admin-menu
          
          # Nettoyer
          cd ..
          rm -rf temp temp.zip
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip