name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create and Modify Archive
        run: |
          # Extraire le nom du dépôt (prend la partie après le /)
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          
          # Créer le dossier cible avec le nom du dépôt
          mkdir -p "$REPO_NAME"
          
          # Copier tous les fichiers du projet dans ce dossier
          # sauf .git et le dossier lui-même
          cp -r $(ls -A | grep -v '^\.git$\|^'"$REPO_NAME"'$') "$REPO_NAME/"
          
          # Créer l'archive avec le dossier renommé
          zip -r release.zip "$REPO_NAME"
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip