name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Archive
        run: |
          git config --global tar.umask 0022
          git config --global tar.prefix "upcoder-admin-menu/"
          git archive --prefix=upcoder-admin-menu/ -o release.zip HEAD
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip